### PR TITLE
Update stage

### PR DESCRIPTION
**Pull request by azu**
Update each stage of proposals.
- [ECMAScript proposal updates @ 2016-10 | ECMAScript Daily](https://ecmascript-daily.github.io/2016/10/02/proposals-updates)

Rename `System.global` to `global`.
- [ES proposal: global](http://www.2ality.com/2016/09/global.html)
- [Rename `System.global` to `global`. · tc39/proposal-global@b72526a](https://github.com/tc39/proposal-global/commit/b72526a0fcdad7332bed738427a830496119d9be)

### CODE REVIEW

**Comment by hemanth** [comment]
Thanks a ton!

**Comment by azu** [comment]
Thanks for merge.
Shall we update TOC too?

**Comment by hemanth** [comment]
[https://github.com/hemanth/es-next/commit/10c81bcdf43d7a6ce31bf322dcc1ed1e97fea1df](done).

**Comment by hemanth** [comment]
Done
https://github.com/hemanth/es-next/commit/10c81bcdf43d7a6ce31bf322dcc1ed1e97fea1df
 :)

**Pull request merged**
